### ISSUE TITLE
Failed to fetch.

### ISSUE THREAD

**Issue by misaellopes01** [Banthonio/angola-prov-localidades#1]
Hi, guys, it seems like this api is down, isn't working...

**Comment by Banthonio** [comment]
Hi, @misaellopes01 , sorry for the late response, we tested and is working, maybe was something with Heroku.

Endpoing e.g: http://angola-prov-localidades.herokuapp.com/v1/provinces/name/benguela

You can check the endpoints on https://angola-prov-localidades.herokuapp.com/api-docs/

![image](https://user-images.githubusercontent.com/64954309/174014301-5f0e7497-8bfc-4123-a543-83cf7b21774c.png)
